### ISSUE TITLE
Singular matrix error when in multinomial case

### ISSUE THREAD

**Issue by Ge0rges** [statdivlab/raoBust#20]
Hi all,

I'm trying to run the following and obtaining a singular matrix issue. See below.

With `strong=False, j=0, penalty=False` I get `R[write to console]: Error in beta_matrix[, k] <- values[((k - 2) * (p + 1) + 1):((k - 1) *  : replacement has zero length` with the following input:

 ```
# X matrix
bottom_middle_top <- matrix(c(
  1, 0, 0,
  0, 1, 0,
  0, 0, 1,
  0, 1, 0,
  0, 0, 1,
  1, 0, 0,
  0, 1, 0,
  0, 0, 1,
  1, 0, 0
), nrow=9, byrow=TRUE)

# Y matrix
matrix_21839 <- matrix(c(
  0, 4, 0, 1058,
  0, 4, 0, 420,
  0, 0, 0, 1,
  0, 0, 0, 106,
  0, 4, 0, 214,
  0, 11, 0, 982,
  0, 0, 0, 23,
  0, 0, 0, 18,
  0, 8, 0, 1260
), nrow=9, byrow=TRUE)
```

With `strong=True, j=False, penalty=False` I get singular matrix error with the following input:

```
# X matrix
bottom_middle_top_2 <- matrix(c(
  1, 0, 0,
  0, 0, 1,
  0, 1, 0,
  0, 0, 1,
  1, 0, 0,
  0, 1, 0,
  0, 0, 1,
  1, 0, 0
), nrow=8, byrow=TRUE)

# Y matrix
matrix_21839_2 <- matrix(c(
  0, 4, 0, 387,
  0, 1, 0, 250,
  0, 0, 0, 1,
  0, 0, 0, 69,
  0, 0, 0, 123,
  0, 4, 0, 427,
  0, 0, 0, 12,
  0, 0, 0, 8,
  0, 2, 0, 389
), nrow=9, byrow=TRUE)
```

**Comment by svteichman** [comment]
Hi @Ge0rges,

Thanks for the reproducible examples! 

For the first one, what hypothesis are you trying to test? The function `multinom_test()` is coded to expect indices for $j\in\{1,\ldots,J\}$, so when $j = 0$ it hits an error because it does not recognize the index 0. I'm glad you mentioned this, we'll add an informative error message for this setting. 

For the second case, I'm not able to run the function `multinom_test()` using `bottom_middle_top_2` as `X` and `matrix_21839_2` as `Y`, because `X` and `Y` have different numbers of rows, and I run into an error that says "Error in multinom_test(X = bottom_middle_top_2, Y = matrix_21839_2, strong = True): Please make sure that X and Y have the same number of observations." Do the rows of your `bottom_middle_top_2` and `matrix_21839_2` correspond to the same samples? Is `matrix_21839_2` missing a row? 

Best,
Sarah

**Comment by Ge0rges** [comment]
Ah thanks @svteichman my python 0-indexing habit caught up to me on that first one. My understanding is that passing `j=1` will test in this case if the last two columns are different to each other taking the first column as baseline. Is that correct? I should note that even in this case there are some cases where I obtain an error such as: ` system is computationally singular: reciprocal condition number = 2.40897e-18`.

Apologies for the error in that example, here's the correct set of offending matrices for `strong=True, j=False, penalty=False`:

```
# X matrix
bottom_middle_top_2 <- matrix(c(
  1, 0, 0,
  0, 0, 1,
  0, 1, 0,
  0, 0, 1,
  1, 0, 0,
  0, 1, 0,
  0, 0, 1,
  1, 0, 0,
  0, 1, 1
), nrow=8, byrow=TRUE)

# Y matrix
matrix_21839_2 <- matrix(c(
  0, 4, 0, 387,
  0, 1, 0, 250,
  0, 0, 0, 1,
  0, 0, 0, 69,
  0, 0, 0, 123,
  0, 4, 0, 427,
  0, 0, 0, 12,
  0, 0, 0, 8,
  0, 2, 0, 389
), nrow=9, byrow=TRUE)
```

**Comment by svteichman** [comment]
Thanks for clarifying. This problem relates to issue #18. There are cases in which we cannot calculate the test statistic as it is defined because we run into a matrix that we need to invert that is either truly singular or computationally singular. This tends to happen especially with small sample sizes. One potential solution to this is to replace the inverse with a generalized inverse, however @adw96 and I want to test this to make sure that we still have type I error rate control and a valid test with this new construction before implementing this. I can start looking into this tomorrow. How often does this error come up in the analyses that you are running?

**Comment by Ge0rges** [comment]
Hi @svteichman, thanks for that information. This happens quite often in my dataset as my typical number of sample size are relatively small (with respect to the examples posted they are similar).

**Comment by svteichman** [comment]
@Ge0rges I was thinking more about your data, and one thing that could be contributing to this problem is having columns in your `Y` matrix with only $0$ counts. In this example above, if I remove the columns that only have $0$ counts across all samples from `matrix_21839_2` and then run `multinom_test(X = bottom_middle_top_2, Y = matrix_21839_2[, c(2, 4)], strong = T, j = F, penalty = F)`, I don't get the same error. I wonder if removing categories with only $0$ counts would also result in tests that complete without errors in some of the other examples that you have that are hitting this error. 

If removing the columns with $0$ counts works, I suppose the next question is if it makes any sense. I don't want this to change your analysis plan or the meaning of the hypotheses that you want to test. In this setting, we would no longer be able to test a weak hypothesis that involves category $j$ for any $j$ such that there are no observed counts in the data, and the strong null hypothesis would essentially be that no covariates have a significant effect on differential abundance for all categories not included the ones that were removed.

**Comment by svteichman** [comment]
Additionally, I've worked on implementing and testing a version of the robust score test that uses a generalized inverse that can be computed when the matrices to be inverted are singular or computationally singular. However, I don't want to push this to `statdivlab/raoBust` without talking it over with Amy to make sure this approach seems statistically valid. For now it is implemented in a branch in my fork of the repository, at https://github.com/svteichman/raoBust/tree/mlr_pr.

**Comment by Ge0rges** [comment]
@svteichman thanks for the explanations. Could you clarify:
> In this setting, we would no longer be able to test a weak hypothesis that involves category  for any  such that there are no observed counts in the data, and the strong null hypothesis would essentially be that no covariates have a significant effect on differential abundance for all categories not included the ones that were removed.

Ultimately if the column is all 0 then it shouldn't affect (in my intuition) whether two covariates (columns in X) are determined to be different since it adds no information, is that interpretation correct?

**Comment by svteichman** [comment]
I agree with your intuition although I think about it slightly differently: if a category (column) is made up of all 0's, then we have no information to determine whether there is a difference in the counts of that category between the covariate defined in X.

**Comment by Ge0rges** [comment]
Hi @svteichman, seems like I'm still running into this issue despite removing the all-zero colum:
```
X <- matrix(c(1, 0, 0,
                    0, 1, 0,
                    0, 0, 1,
                    0, 1, 0,
                    0, 0, 1,
                    1, 0, 0,
                    0, 1, 0,
                    0, 0, 1,
                    1, 0, 0), 
                  nrow = 9, ncol = 3, byrow = TRUE)

Y <- matrix(c(2, 527,
                    11, 615,
                    0, 3,
                    1, 240,
                    3, 493,
                    6, 627,
                    0, 44,
                    0, 47,
                    5, 559), 
                  nrow = 9, ncol = 2, byrow = TRUE)

<simpleError in solve.default(I2): system is computationally singular: reciprocal condition number = 4.36772e-17>
```

**Comment by svteichman** [comment]
This is good to know. I have one approach to avoid this problem, although I want to chat with Amy about it in our next meeting, before implementing it here. I'll update this issue after that.

**Comment by svteichman** [comment]
Hi @Ge0rges, the implementation of the score test using a pseudo-inverse matrix is now updated in `raoBust`. You can use it by running `multinom_test()` with the argument `pseudo_inv = TRUE`. Also, I chatted with Amy about this, and she recommended not dropping the columns that are made up of 0's. Let me know if you run into any new computational issues with the `pseudo_inv = TRUE` argument.

**Comment by Ge0rges** [comment]
Thanks @svteichman that seems to work on a few hundred sets. I'm going to run the whole dataset and let you know if I run into any issues. I'm curious what was the logic behind keeping columns of 0s?

**Comment by svteichman** [comment]
The argument is that the categories represented by the columns of $Y$ are true biological categories, and removing them will change the parameter matrix, and the interpretation of the set of parameters as well as the null and alternative hypothesis. And even though (due to small sample size) we don't have data to estimate differences in these categories of all 0's between the covariate levels, we still want to represent the categories that occur in our population. And with the generalized inverse implementation, these columns of only 0's shouldn't cause problems computationally.
